/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author oscar
 */
public class frm_clients extends javax.swing.JFrame{
    private final int userRole;
    private final String userName;
    DefaultTableModel client;
    private final Connection con = DBConnection.getConnection(); // Saving MYSQL Database connection into a variable
    /**
     * Creates new form frm_main
     * @param userRole
     * @param userName
     */
    public frm_clients(int userRole, String userName) {
        initComponents();
        
        this.userRole = userRole;
        this.userName = userName;
                
        this.client = (DefaultTableModel) table_clients.getModel();

        mostrarTabla("");

    }
    
    private void mostrarTabla(String valorCliente){
        refrescarTabla();
        String[] columnNames = {"Nombre", "Apellidos", "Cedula", "Telefono", "Direccion", "Universidad" };
        client = new DefaultTableModel(columnNames, 0); // Setting the column names of the Table Model;
        String sql;
        if(valorCliente.equals("")){
            sql = "SELECT Nombre, Apellidos, Cedula, Telefono, Direccion, Universidad FROM cliente";
        } else {
            sql = "SELECT Nombre, Apellidos, Cedula, Telefono, Direccion, Universidad FROM cliente WHERE Nombre = '"+ valorCliente+"'";
        }
        
        try {
            
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            
           while(rs.next()){
                String Nombre = rs.getString(1);
                String Apellidos = rs.getString(2);
                String Cedula = rs.getString(3);
                String Telefono = rs.getString(4);
                String Direccion = rs.getString(5);
                String Universidad = rs.getString(6);
                
                
                String[] data = {Nombre, Apellidos, Cedula, Telefono, Direccion, Universidad}; // Saving one row of data
                
                client.addRow(data); // Adding the row to the Table Model
                
                
            }
            table_clients.setModel(client);
        } catch(SQLException ex){
            String err = ex.toString(); // Saving the error to a variable while converting it into a string
            
            JOptionPane.showConfirmDialog(this, err);
        }

    }
    private void refrescarTabla(){
        client.setColumnCount(0);
        client.setRowCount(0);
        table_clients.revalidate();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_sidebar = new javax.swing.JPanel();
        btn_exit = new javax.swing.JButton();
        jp_panel = new javax.swing.JPanel();
        jscroll_table = new javax.swing.JScrollPane();
        table_clients = new javax.swing.JTable();
        lbl_panel = new javax.swing.JLabel();
        lbl_nombre = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        lbl_apellidos = new javax.swing.JLabel();
        txt_apellidos = new javax.swing.JTextField();
        btn_delete = new javax.swing.JButton();
        btn_create = new javax.swing.JButton();
        btn_modify = new javax.swing.JButton();
        lbl_telefono = new javax.swing.JLabel();
        lbl_cedula = new javax.swing.JLabel();
        txt_cedula = new javax.swing.JTextField();
        txt_telefono = new javax.swing.JTextField();
        lbl_universidad = new javax.swing.JLabel();
        lbl_direccion = new javax.swing.JLabel();
        txt_direccion = new javax.swing.JTextField();
        txt_universidad = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jp_sidebar.setBackground(new java.awt.Color(0, 102, 102));

        btn_exit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_exit.setForeground(new java.awt.Color(255, 0, 0));
        btn_exit.setText("<-");
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_sidebarLayout = new javax.swing.GroupLayout(jp_sidebar);
        jp_sidebar.setLayout(jp_sidebarLayout);
        jp_sidebarLayout.setHorizontalGroup(
            jp_sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_sidebarLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btn_exit)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jp_sidebarLayout.setVerticalGroup(
            jp_sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_sidebarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_exit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        table_clients.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_clients.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_clientsMouseClicked(evt);
            }
        });
        jscroll_table.setViewportView(table_clients);

        lbl_panel.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lbl_panel.setText("Panel de Clientes");

        lbl_nombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_nombre.setText("Nombre:");

        lbl_apellidos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_apellidos.setText("Apellidos:");

        btn_delete.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_delete.setText("Borrar");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_create.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_create.setText("Crear");
        btn_create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_createActionPerformed(evt);
            }
        });

        btn_modify.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_modify.setText("Modificar");
        btn_modify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modifyActionPerformed(evt);
            }
        });

        lbl_telefono.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_telefono.setText("Telefono:");

        lbl_cedula.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_cedula.setText("Cedula:");

        lbl_universidad.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_universidad.setText("Universidad:");

        lbl_direccion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_direccion.setText("Direccion:");

        javax.swing.GroupLayout jp_panelLayout = new javax.swing.GroupLayout(jp_panel);
        jp_panel.setLayout(jp_panelLayout);
        jp_panelLayout.setHorizontalGroup(
            jp_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_panel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jscroll_table, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
            .addGroup(jp_panelLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(jp_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_panelLayout.createSequentialGroup()
                        .addGroup(jp_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jp_panelLayout.createSequentialGroup()
                                .addGroup(jp_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_apellidos)
                                    .addComponent(lbl_nombre)
                                    .addComponent(lbl_telefono)
                                    .addComponent(lbl_cedula)
                                    .addComponent(lbl_direccion))
                                .addGap(23, 23, 23))
                            .addGroup(jp_panelLayout.createSequentialGroup()
                                .addComponent(lbl_universidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(5, 5, 5)))
                        .addGroup(jp_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txt_apellidos, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                            .addComponent(txt_cedula, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_telefono, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_direccion, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_universidad, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_nombre)))
                    .addGroup(jp_panelLayout.createSequentialGroup()
                        .addComponent(btn_create, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_modify)
                        .addGap(18, 18, 18)
                        .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jp_panelLayout.setVerticalGroup(
            jp_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_panelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lbl_panel)
                .addGap(18, 18, 18)
                .addComponent(jscroll_table, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jp_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nombre)
                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_apellidos)
                    .addComponent(txt_apellidos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_cedula))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_telefono))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_direccion)
                    .addComponent(txt_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_universidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_universidad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_create, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_modify, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jp_sidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jp_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jp_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jp_sidebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        frm_main Main = new frm_main(userName, userRole);
        Main.setLocationRelativeTo(null);
        Main.pack();
        Main.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_btn_exitActionPerformed

    private void btn_modifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modifyActionPerformed
        String Nombre = txt_nombre.getText();
        String Apellidos = txt_apellidos.getText();
        String Cedula = txt_cedula.getText();
        String Telefono = txt_telefono.getText();
        String Direccion = txt_direccion.getText();
        String Universidad = txt_universidad.getText();
  
        String sql = "UPDATE cliente SET Nombre = '"+ Nombre + "', Apellidos = '" + Apellidos + "', Cedula = '" + Cedula + "', Telefono = '" + Telefono + "', Direccion = '" + Direccion + "', Universidad ='" + Universidad + "' WHERE Nombre = '"+ Nombre + "' AND Apellidos = '" + Apellidos + "' OR Cedula = '" + Cedula + "' OR Telefono = " + Telefono + " OR Direccion = '" + Direccion + "'";
        
        try{
            Statement st = con.createStatement();
            st.executeUpdate(sql);
            
            txt_nombre.setText("");
            txt_apellidos.setText("");
            txt_cedula.setText("");
            txt_telefono.setText("");
            txt_direccion.setText("");
            txt_universidad.setText(""); //Cleaning all the textfields
            
        } catch(SQLException ex) {
            String err = ex.toString(); // Saving the error to a variable while converting it into a string
            
            JOptionPane.showConfirmDialog(this, err);
        }
        mostrarTabla("");        
    }//GEN-LAST:event_btn_modifyActionPerformed

    private void btn_createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_createActionPerformed
        int id = 0;
        String Nombre = txt_nombre.getText();
        String Apellidos = txt_apellidos.getText();
        String Cedula = txt_cedula.getText();
        String Telefono = txt_telefono.getText();
        String Direccion = txt_direccion.getText();
        String Universidad = txt_universidad.getText();
        
        String sql = "SELECT id_cliente, Nombre FROM cliente ORDER BY id_cliente DESC LIMIT 1";
        
        try{
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            rs.beforeFirst();
            if(rs.next()){
                id = rs.getInt(1);
                id += 1;
            }else{
                id = 1;
            }
            
        }catch(SQLException ex) {
            String err = ex.toString(); // Saving the error to a variable while converting it into a string
            
            JOptionPane.showConfirmDialog(this, err);
        }
  
        sql = "INSERT INTO cliente(id_cliente, Nombre, Apellidos, Cedula, Telefono, Direccion, Universidad) VALUES(" + id + ", '"+ Nombre + "', '" + Apellidos + "', '" + Cedula + "', '" + Telefono + "', '" + Direccion + "', '" + Universidad + "')";
        
        try{
            Statement st = con.createStatement();
            st.executeUpdate(sql);
            
            txt_nombre.setText("");
            txt_apellidos.setText("");
            txt_cedula.setText("");
            txt_telefono.setText("");
            txt_direccion.setText("");
            txt_universidad.setText(""); //Cleaning all the textfields
            
        } catch(SQLException ex) {
            String err = ex.toString(); // Saving the error to a variable while converting it into a string
            
            JOptionPane.showConfirmDialog(this, err);
        }
        mostrarTabla("");

    }//GEN-LAST:event_btn_createActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        String Nombre = txt_nombre.getText();
        String Apellidos = txt_apellidos.getText();
        String Cedula = txt_cedula.getText();
  
        String sql = "DELETE FROM cliente WHERE Nombre ='"+ Nombre + "' AND Apellidos = '" + Apellidos + "' AND Cedula = '" + Cedula + "'";
        
        try{
            Statement st = con.createStatement();
            st.executeUpdate(sql);
            
            txt_nombre.setText("");
            txt_apellidos.setText("");
            txt_cedula.setText("");
            txt_telefono.setText("");
            txt_direccion.setText("");
            txt_universidad.setText(""); //Cleaning all the textfields
        } catch(SQLException ex) {
            String err = ex.toString(); // Saving the error to a variable while converting it into a string
            
            JOptionPane.showConfirmDialog(this, err);
        }
        mostrarTabla("");// TODO add your handling code here:
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void table_clientsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_clientsMouseClicked
               
       int SelectedRow = table_clients.getSelectedRow();
       
       txt_nombre.setText(table_clients.getValueAt(SelectedRow, 0).toString());
       txt_apellidos.setText(table_clients.getValueAt(SelectedRow, 1).toString());
       txt_cedula.setText(table_clients.getValueAt(SelectedRow, 2).toString());
       txt_telefono.setText(table_clients.getValueAt(SelectedRow, 3).toString());
       txt_direccion.setText(table_clients.getValueAt(SelectedRow, 4).toString());
       txt_universidad.setText(table_clients.getValueAt(SelectedRow, 5).toString());
       
    }//GEN-LAST:event_table_clientsMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_create;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_modify;
    private javax.swing.JPanel jp_panel;
    private javax.swing.JPanel jp_sidebar;
    private javax.swing.JScrollPane jscroll_table;
    private javax.swing.JLabel lbl_apellidos;
    private javax.swing.JLabel lbl_cedula;
    private javax.swing.JLabel lbl_direccion;
    private javax.swing.JLabel lbl_nombre;
    private javax.swing.JLabel lbl_panel;
    private javax.swing.JLabel lbl_telefono;
    private javax.swing.JLabel lbl_universidad;
    private javax.swing.JTable table_clients;
    private javax.swing.JTextField txt_apellidos;
    private javax.swing.JTextField txt_cedula;
    private javax.swing.JTextField txt_direccion;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_telefono;
    private javax.swing.JTextField txt_universidad;
    // End of variables declaration//GEN-END:variables
}
