/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.event.KeyEvent;
import java.net.URL;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer; 

/**
 *
 * @author oscar
 */
public class frm_user extends javax.swing.JFrame {
    private final int userRole;
    private final String userName;
    DefaultTableModel users;
    private final Connection con = DBConnection.getConnection(); // Saving MYSQL Database connection into a variable
    
    /**
     * Creates new form frm_main
     * @param userRole
     * @param userName
     */
    
    public frm_user(int userRole, String userName) {
        initComponents();
        
        this.userRole = userRole;
        this.userName = userName;
        this.users = (DefaultTableModel) table_users.getModel();
        
        mostrarTabla("");
        
    }
    private void mostrarTabla(String valor){
        refrescarTabla();
        String[] columnNames = {"Correo", "Nick", "Password", "Rol" };
        users = new DefaultTableModel(columnNames, 0); // Setting the column names of the Table Model;
        String sql;
        if(valor.equals("")){
            sql = "SELECT correoUsuario, nickUsuario, passwordUsuario, rolUsuario FROM usuario";
        } else {
            sql = "SELECT correoUsuario, nickUsuario, passwordUsuario, rolUsuario FROM usuario WHERE correoUsuario = '"+ valor +"'";
        }
        
        try {
            
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            
           while(rs.next()){
                String correoUsuario = rs.getString(1);
                String nickUsuario = rs.getString(2);
                String passwordUsuario = rs.getString(3);
                String rolUsuario = String.valueOf(rs.getInt(4));
                
                String[] data = {correoUsuario, nickUsuario, passwordUsuario, rolUsuario}; // Saving one row of data
                
                users.addRow(data); // Adding the row to the Table Model
                
                
            }
           table_users.setModel(users);
        } catch(SQLException ex){
            String err = ex.toString(); // Saving the error to a variable while converting it into a string
            
            JOptionPane.showConfirmDialog(this, err);
        }

    }
    private void refrescarTabla(){
        users.setColumnCount(0);
        users.setRowCount(0);
        table_users.revalidate();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_sidebar = new javax.swing.JPanel();
        btn_exit = new javax.swing.JButton();
        jp_panel = new javax.swing.JPanel();
        jscroll_table = new javax.swing.JScrollPane();
        table_users = new javax.swing.JTable();
        lbl_panel = new javax.swing.JLabel();
        lbl_correo = new javax.swing.JLabel();
        txt_correo = new javax.swing.JTextField();
        lbl_usuario = new javax.swing.JLabel();
        txt_usuario = new javax.swing.JTextField();
        lbl_password = new javax.swing.JLabel();
        lbl_rol = new javax.swing.JLabel();
        cmb_rol = new javax.swing.JComboBox<>();
        btn_delete = new javax.swing.JButton();
        btn_create = new javax.swing.JButton();
        btn_modify = new javax.swing.JButton();
        txtp_password = new javax.swing.JPasswordField();
        btn_form = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jp_sidebar.setBackground(new java.awt.Color(0, 102, 102));

        btn_exit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_exit.setForeground(new java.awt.Color(255, 0, 0));
        btn_exit.setText("<-");
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_sidebarLayout = new javax.swing.GroupLayout(jp_sidebar);
        jp_sidebar.setLayout(jp_sidebarLayout);
        jp_sidebarLayout.setHorizontalGroup(
            jp_sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_sidebarLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btn_exit)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jp_sidebarLayout.setVerticalGroup(
            jp_sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_sidebarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_exit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        table_users.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_users.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_usersMouseClicked(evt);
            }
        });
        jscroll_table.setViewportView(table_users);

        lbl_panel.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lbl_panel.setText("Panel de Usuarios");

        lbl_correo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_correo.setText("Correo:");

        txt_correo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_correoKeyPressed(evt);
            }
        });

        lbl_usuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_usuario.setText("Usuario:");

        txt_usuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_usuarioKeyTyped(evt);
            }
        });

        lbl_password.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_password.setText("Password:");

        lbl_rol.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_rol.setText("Rol:");

        cmb_rol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona:", "Empleado", "Administrador" }));

        btn_delete.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_delete.setText("Borrar");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_create.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_create.setText("Crear");
        btn_create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_createActionPerformed(evt);
            }
        });

        btn_modify.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_modify.setText("Modificar");
        btn_modify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modifyActionPerformed(evt);
            }
        });

        btn_form.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_form.setText("Reporte");
        btn_form.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_formActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_panelLayout = new javax.swing.GroupLayout(jp_panel);
        jp_panel.setLayout(jp_panelLayout);
        jp_panelLayout.setHorizontalGroup(
            jp_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jscroll_table)
                .addContainerGap())
            .addGroup(jp_panelLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(jp_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_panelLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(lbl_panel))
                    .addGroup(jp_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jp_panelLayout.createSequentialGroup()
                            .addComponent(btn_create, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btn_modify)
                            .addGap(18, 18, 18)
                            .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btn_form, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jp_panelLayout.createSequentialGroup()
                            .addGroup(jp_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbl_correo)
                                .addComponent(lbl_usuario)
                                .addComponent(lbl_password)
                                .addComponent(lbl_rol))
                            .addGap(21, 21, 21)
                            .addGroup(jp_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtp_password)
                                .addComponent(txt_usuario, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_correo, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cmb_rol, 0, 393, Short.MAX_VALUE)))))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jp_panelLayout.setVerticalGroup(
            jp_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_panelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lbl_panel)
                .addGap(18, 18, 18)
                .addComponent(jscroll_table, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jp_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_correo)
                    .addComponent(txt_correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_usuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_password)
                    .addComponent(txtp_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_rol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_rol))
                .addGap(18, 18, 18)
                .addGroup(jp_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_modify, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_form, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_create, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jp_sidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jp_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jp_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jp_sidebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        String correo = txt_correo.getText();
        String usuario = txt_usuario.getText();
                
        String sql = "DELETE FROM usuario WHERE correoUsuario = '" + correo + "' AND nickUsuario = '" + usuario + "'";
        
        try{
            Statement st = con.createStatement();
            st.executeUpdate(sql);
         
        txt_correo.setText("");
        txt_usuario.setText("");
        txtp_password.setText("");
        cmb_rol.setSelectedIndex(0); // Cleaning the textfields 
            
        } catch(SQLException ex) {
            String err = ex.toString(); // Saving the error to a variable while converting it into a string
            
            JOptionPane.showConfirmDialog(this, err);
        }
        mostrarTabla("");
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_createActionPerformed
        String correo = txt_correo.getText();
        String usuario = txt_usuario.getText();
        String password = new String(txtp_password.getPassword());
        int rol;
        switch(cmb_rol.getSelectedIndex()){
            case 1:
                rol = 0;
                break;
            case 2:
                rol = 1;
                break;
            default:
                rol = 1;
                break;
        }
          
                
        String sql = "INSERT INTO usuario(correoUsuario, nickUsuario, passwordUsuario, rolUsuario) VALUES('"+ correo + "', '" + usuario + "', '" + password + "', " + rol + ")";
        
        try{
            Statement st = con.createStatement();
            st.executeUpdate(sql);
            
         txt_correo.setText("");
         txt_usuario.setText("");
         txtp_password.setText("");
         cmb_rol.setSelectedIndex(0); // Cleaning the textfields
            
        } catch(SQLException ex) {
            String err = ex.toString(); // Saving the error to a variable while converting it into a string
            
            JOptionPane.showConfirmDialog(this, err);
        }
        mostrarTabla("");
    }//GEN-LAST:event_btn_createActionPerformed

    private void btn_modifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modifyActionPerformed
        String correo = txt_correo.getText();
        String usuario = txt_usuario.getText();
        String password = new String(txtp_password.getPassword());
        int rol;
        switch(cmb_rol.getSelectedIndex()){
            case 1:
                rol = 0;
                break;
            case 2:
                rol = 1;
                break;
            default:
                rol = 1;
                break;
        } // Getting the value from combo box of user's rol
        
        String sql = "UPDATE usuario SET correoUsuario ='" + correo + "', nickUsuario = '" + usuario + "', passwordUsuario = '" + password + "', rolUsuario =" + rol + " WHERE correoUsuario = '" + correo + "' OR nickUsuario = '" + usuario + "'";
        
        try{
            Statement st = con.createStatement();
            st.executeUpdate(sql);
            
         txt_correo.setText("");
         txt_usuario.setText("");
         txtp_password.setText("");
         cmb_rol.setSelectedIndex(0); //Cleaning the textfields
            
        } catch(SQLException ex) {
            String err = ex.toString(); // Saving the error to a variable while converting it into a string
            
            JOptionPane.showConfirmDialog(this, err);
        }
        
        mostrarTabla("");
    }//GEN-LAST:event_btn_modifyActionPerformed

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        frm_main Main = new frm_main(userName, userRole);
        Main.setLocationRelativeTo(null);
        Main.pack();
        Main.setVisible(true);
        
        this.dispose();
        
        
    }//GEN-LAST:event_btn_exitActionPerformed

    private void txt_correoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_correoKeyPressed
        try{
            if(evt.getKeyCode() == KeyEvent.VK_ENTER){
                String b = txt_correo.getText();
                
                mostrarTabla(b);
            }
        } catch (Exception ex){
            String err = ex.toString(); // Saving the error to a variable while converting it into a string
            
            JOptionPane.showConfirmDialog(this, err);
            Logger.getLogger(frm_user.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txt_correoKeyPressed

    private void txt_usuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_usuarioKeyTyped
        textFieldsRestrictions.justLetters(evt);
    }//GEN-LAST:event_txt_usuarioKeyTyped

    private void table_usersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_usersMouseClicked
       // Getting the values of the table, when a row is clicked by the user.
        int SelectedRow = table_users.getSelectedRow();
       
       txt_correo.setText(table_users.getValueAt(SelectedRow, 0).toString());
       txt_usuario.setText(table_users.getValueAt(SelectedRow, 1).toString());
       txtp_password.setText(table_users.getValueAt(SelectedRow, 2).toString());
       
       int rolSelected = Integer.parseInt((String) table_users.getValueAt(SelectedRow, 3));
       switch(rolSelected){
           case 0:
               cmb_rol.setSelectedIndex(1);
               break;
           case 1:
               cmb_rol.setSelectedIndex(2);
               break;
           default:
               cmb_rol.setSelectedIndex(0);
       }
       
    }//GEN-LAST:event_table_usersMouseClicked

    private void btn_formActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_formActionPerformed

        try{
          JasperReport jr = (JasperReport) JRLoader.loadObject(getClass().getResource("/reportes/reporte_usuario.jasper"));
          //Codigo en comentario es agregando los datos directamente
          Map parametros = new HashMap<>();
          parametros.put("Titulo", "Reporte de Usuarios");
            

          JasperPrint jp = JasperFillManager.fillReport(jr, parametros, con);
          JasperViewer jv = new JasperViewer(jp, false);
          jv.setVisible(true); 
        }
        catch (JRException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
            System.out.println(ex);
        }
    }//GEN-LAST:event_btn_formActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_create;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_form;
    private javax.swing.JButton btn_modify;
    private javax.swing.JComboBox<String> cmb_rol;
    private javax.swing.JPanel jp_panel;
    private javax.swing.JPanel jp_sidebar;
    private javax.swing.JScrollPane jscroll_table;
    private javax.swing.JLabel lbl_correo;
    private javax.swing.JLabel lbl_panel;
    private javax.swing.JLabel lbl_password;
    private javax.swing.JLabel lbl_rol;
    private javax.swing.JLabel lbl_usuario;
    private javax.swing.JTable table_users;
    private javax.swing.JTextField txt_correo;
    private javax.swing.JTextField txt_usuario;
    private javax.swing.JPasswordField txtp_password;
    // End of variables declaration//GEN-END:variables
}
